# Versão final usando os nomes do seu projeto e o ambiente PHP nativo do Render

services:
  # 1. O Serviço da Aplicação Web (Laravel)
  - type: web
    name: estacoes-estoque # <-- Nome do seu app
    env: php              # <-- Usando o ambiente PHP nativo (mais simples)
    plan: free

    # Comandos para build, migração e inicialização
    buildCommand: "composer install --no-dev --optimize-autoloader"
    preDeployCommand: "php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port ${PORT}"

    # Variáveis de Ambiente
    envVars:
      - key: APP_KEY
        generateValue: true # É mais seguro deixar o Render gerar uma chave nova
      - key: APP_URL
        fromService:
          type: web
          name: estacoes-estoque # <-- Nome do seu app
          property: url
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: lojamanager # <-- Nome do seu banco de dados
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql

  # 2. O Serviço do Banco de Dados PostgreSQL
  - type: pserv
    name: lojamanager # <-- Nome do seu banco de dados
    plan: free
