# Arquivo de configuração "Blueprint" do Render (Versão Final Corrigida)
services:
  # O serviço do banco de dados (inalterado)
  - type: pserv
    name: lojamanager
    plan: free

  # O serviço da aplicação web
  - type: web
    name: estacoes-estoque
    runtime: docker
    dockerfilePath: ./Dockerfile
    # AQUI ESTÁ A CORREÇÃO FINAL:
    # Dizemos ao Render para executar nosso script de inicialização.
    startCommand: "./start.sh"
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: estacoes-estoque
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: meu-app-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: meu-app-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: meu-app-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: meu-app-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: meu-app-db
          property: password
      - key: base64:N557P0A7ZKbUAmna9L516DhZi0vPln/ayoJ48b9EWZI=
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
