# Arquivo Blueprint final para o projeto estacoes-manager

# Define os serviços e bancos de dados a serem criados.
services:
  # 1. O Serviço da Aplicação Web (Laravel)
  - type: web
    name: estacoes-manager
    runtime: docker
    repo: https://github.com/SenhorArroz/Sistema-de-controle-de-estoque-cliente-fornecedor-para-lojas-de-roupa
    plan: free
    region: oregon # Garanta que a região é a mesma do banco de dados
    autoDeploy: true # Opcional: faz deploy a cada push na branch principal

    # Comando para iniciar o container, que executa nosso script.
    dockerCommand: "./start.sh"
    dockerContext: .
    dockerfilePath: ./Dockerfile

    # Variáveis de Ambiente essenciais para o Laravel
    envVars:
      - key: APP_KEY
        generateValue: true # Deixa o Render gerar uma chave segura
      - key: APP_URL
        fromService:
          type: web
          name: estacoes-manager
          property: url # Pega a URL do serviço automaticamente
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL # Conecta ao banco de dados de forma simples
        fromDatabase:
          name: estacoes-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Adicione outras variáveis que seu app precise (ex: MAIL_*, AWS_*)
      # - key: MAIL_MAILER
      #   value: smtp

# Define o banco de dados
databases:
  - name: estacoes-db
    databaseName: lojamanager
    user: lojamanager_user
    plan: free
    region: oregon
    postgresMajorVersion: "14" # <-- RECOMENDADO: Usar uma versão mais estável
