# Blueprint final: Web Service + Migration Worker

services:
  # 1. O Serviço do Banco de Dados PostgreSQL
  - type: pserv
    name: lojamanager
    plan: free

  # 2. O Serviço da Aplicação Web (Seu site Laravel)
  # Este serviço agora NÃO tem um startCommand, então ele usará o comando
  # padrão da imagem Docker, que é iniciar o servidor web.
  - type: web
    name: estacoes-estoque
    env: docker # Usaremos 'env: docker' que é o novo padrão para runtime
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: estacoes-estoque
          property: url
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: lojamanager
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql

  # 3. O Worker para Rodar as Migrações
  # Este é um serviço separado que só roda quando mandamos.
  - type: worker
    name: migrate-worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: "php artisan migrate --force"
    # Este worker não precisa ficar rodando, então damos poucos recursos.
    instanceCount: 0 # Começa desligado
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: lojamanager
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
